services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hezzl
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./migrations/goods_postgres_migrations.sql:/docker-entrypoint-initdb.d/goods_postgres_migrations.sql

  redis:
    image: redis:7-alpine
    
  nats:
    image: nats:2.10-alpine

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    environment:
      CLICKHOUSE_DB: "default"
      CLICKHOUSE_PASSWORD: "default"
    volumes:
      - ./ch_data:/var/lib/clickhouse
      - ./migrations/goods_log_clickhouse.sql:/docker-entrypoint-initdb.d/goods_log_clickhouse.sql

  goods_crud:
    depends_on: 
      - postgres
      - redis
      - nats
      - clickhouse
    build: .
    ports: 
      - "20001:20001"
